'''
Parsers for meta data.

:since: 25/04/2014
:author: oblivion
'''
'''
Meta data
=========

Meta data are stored in a simple dictionary. This makes it possible to add
custom meta data by simply adding them to the input files.
Some meta data are generated by ssg itself and these are reserved:

file
    The full path and name of the file the meta data belongs to.

template
    Specify the template to use for this file, else use 'index.html'
'''
META_PARSERS = list()
'''List of active meta data parsers.'''


class MetaParserBase(object):
    '''Base class for metadata parsers. '''
    def __init__(self):
        '''Constructor'''
        pass

    def parse(self, path):
        '''Parse something and return meta data in a dictionary.

        :param path: Path to content.
        :type path: string
        :returns: dict with meta data.
        '''
        raise NotImplementedError('Must be implemented in a derived class')

