'''
Meta data are stored in a simple dictionary. This makes it possible to add
custom meta data by simply adding them to the input files.
Some meta data are generated by ssg itself and these are reserved.

Reserved meta data keywords
---------------------------

file
    The full path and name of the file the meta data belongs to.

template
    Specify the template to use for this file, else use 'index.html'

type
    Type of the content in the file.


Meta data extensions
--------------------
Meta data extensions extract meta data from the name of the file, the content of
the file, or some other useful data. Meta data extensions all inherit
*MetaParserBase*.
'''
META_PARSERS = list()
'''List of active meta data parsers.'''


class MetaParserBase(object):
    '''Base class for metadata parsers. '''
    def __init__(self):
        '''Constructor'''
        pass

    def parse(self, path):
        '''Parse something and return meta data in a dictionary.

        :param path: Path to content.
        :type path: string
        :returns: dict with meta data.
        '''
        raise NotImplementedError('Must be implemented in a derived class')

