'''
BlogIndexGenerator
==================

Generate an ``index.html`` file from a template of the same name. This is
useful for blogs and pages for indexing articles, creating the index on the
fly.
**If content is of type 'post' the 'post.html' template is used**, if no
template explicitly set in the meta data of the content.
**Content is sorted by date**
Adds the config key "POSTPERINDEX", to set the number of posts per index page.
:since: 06/05/2014
:author: oblivion
'''
from datetime import datetime
from ssg import generator
from ssg.log import logger
from ssg.settings import SETTINGS


class BlogIndexGenerator(generator.GeneratorBase):
    '''
    Generate an ``index.html`` from a template.
    '''
    def __init__(self):
        '''
        Constructor
        '''
        generator.GeneratorBase.__init__(self)

    def create_index(self, page=''):
        '''Create an index(n).html from a context.

        :param page: If the index spans multiply pages, gives page number.
        :type page: string
        '''
        # Create meta data for index
        # Create a dictionary for metadata
        metadata = dict()
        # Omit page number from first index file
        if page == 1:
            metadata['file'] = SETTINGS['CONTENTDIR'] + '/index.html'
        else:
            metadata['file'] = SETTINGS['CONTENTDIR'] + '/index' + str(page) + '.html'
        metadata['title'] = 'index'
        metadata['date'] = datetime.now()
        metadata['type'] = 'index'
        metadata['template'] = 'index'
        # Create a contents node for the index
        content = dict()
        # Add meta data
        content['metadata'] = metadata
        # Empty content
        content['content'] = ''
        logger.debug('Autogenerated content: ' + str(content))
        # Add contents to context
        return(content)

    def run(self, context):
        '''Run the generator.

        :param context: The context of the site.
        :type context: ssg.context.Context
        '''
        logger.debug('Running BlogIndexGenerator extension.')
        # Apply post template to all content that has type post, if no template
        # is set.
        for content in context.contents:
            # Check if meta data has 'type'
            if 'type' in content['metadata'].keys():
                # Check if type is 'post'
                if content['metadata']['type'] == 'post':
                    # Check if template is set
                    if 'template' not in content['metadata'].keys():
                        # Set template to 'post'
                        content['metadata']['template'] = 'post'
        # Sort by date
        context.contents = sorted(context.contents,
                                  key=lambda c: c['metadata']['date'],
                                  reverse=True)
        # Check if we're supposed to use pagination
        if 'POSTPERINDEX' in SETTINGS.keys():
            logger.debug(str(SETTINGS['POSTPERINDEX']) + ' post per page.')
            # Keep track of the page number
            page = 1
            # Create a list of posts
            posts = list()
            # Run trough all content
            for content in context.contents:
                # Split by 'POSTSPERINDEX', and create indices
                if len(posts) <= SETTINGS['POSTPERINDEX']:
                    logger.debug('Adding post to page ' + str(page))
                    posts.append(content)
                else:
                    logger.debug('Creating new page.')
                    index = self.create_index(page=page)
                    # Add local context
                    index['context'] = {'context': context,
                                          'posts': posts,
                                          'content': index}
                    page += 1
                    context.contents.append(index)
                    # New posts list
                    posts = list()
            # Get any remaining posts
            if len(posts) > 0:
                logger.debug('Last page is ' + str(len(posts)) + 'posts long.')
                index = self.create_index(page=page)
                index['context'] = {'context': context,
                                      'posts': posts,
                                      'content': index}
                context.contents.append(index)
        else:
            logger.debug('No pagination.')
            index = self.create_index()
            index['context'] = {'context': context,
                                  'posts': index,
                                  'content': index}
            context.contents.append(index)


# Add CategoriMetaParser to list of parsers
generator.GENERATORS.append(BlogIndexGenerator())
