#! /usr/bin/env python
'''
Main file for Static Site Generator
'''
import os
import ssg


def main():
    '''
    The entry point.
    '''
    try:
        ssg.init(True)
        root = os.getcwd()
        ssg.process_content(root)
    finally:
        ssg.close()


if __name__ == '__main__':
    main()
