#! /usr/bin/env python
'''
Main file for Static Site Generator
'''
import os
import argparse
import ssg
from ssg.log import logger
from ssg.settings import SETTINGS


def main():
    '''
    The entry point.
    '''
    # Parse command line
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("-d", "--debug",
                            action="store_true", dest="debug", default=False,
                            help="Print debug information")
    arg_parser.add_argument("-s", "--site_url", help="Set the site URL.")
    arg_parser.add_argument("--write-all", action="store_true",
                            dest="write_all", default=False,
                            help="Write all files, instead of updating."
                            )
    args = arg_parser.parse_args()

    try:
        ssg.init(args.debug)
        # Set site URL if specified on the command line
        if not args.site_url == None:
            SETTINGS['SITEURL'] = args.site_url
        logger.info("Static Site Generator V." + ssg.__version__)
        root = os.getcwd()
        if args.write_all:
            ssg.run(root, False)
        else:
            ssg.run(root, True)
    finally:
        ssg.close()


if __name__ == '__main__':
    main()
